version: "3"

services:
  puppeteer:
    build: .
    image: entrptaher/exp-puppeteer-performance
    command: bash script.sh
    ports: 
      - "3000:3000"
    volumes:
      - yarn_cache:/yarn

volumes:
  yarn_cache: